# name: terraformWorkflow

# on: 
#   push: 
#     branches: 
#     - 'main'
#     - 'feature'
# env:
#   environment: dev
  
# jobs:
#   my_first_job:
#   runs-on: ubuntu-latest
#   name: terraformInstall
#     steps: 
#      - name: PowerShell script
#        uses: Amadevus/pwsh-script@v2.0.3
#        with:
#         # PowerShell script to execute in Actions-hydrated context
#         script: terraform init
#      - name: Azure Login
#        uses: Azure/login@v2.3.0
#        with:
  
                
    
      
      
